name: Deploy

on:
  push:
    branches: -dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    name: Build and publish Docker container.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker.
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image.
        run: docker build -t kyve/evm-dev:latest .

      - name: Push to Docker hub.
        run: docker push -a kyve/evm-dev
